language: r
cache: packages
sudo: false

r:
  - oldrel
  - release
  - devel
os:
  - linux

compiler:
  - gcc

install:
  - R -e 'install.packages(c("data.table", "purrr", "RcppArmadillo", "knitr", "ggplot2", "rmarkdown", "testthat", "covr", "pkgdown"))'

after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
