// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// raw_noise
NumericVector raw_noise(int timesteps, double mu, double sigma, double phi);
RcppExport SEXP _colorednoise_raw_noise(SEXP timestepsSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP phiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type timesteps(timestepsSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type phi(phiSEXP);
    rcpp_result_gen = Rcpp::wrap(raw_noise(timesteps, mu, sigma, phi));
    return rcpp_result_gen;
END_RCPP
}
// timeseries
DataFrame timeseries(int start, int timesteps, double survPhi, double fecundPhi, double survMean, double survSd, double fecundMean, double fecundSd);
RcppExport SEXP _colorednoise_timeseries(SEXP startSEXP, SEXP timestepsSEXP, SEXP survPhiSEXP, SEXP fecundPhiSEXP, SEXP survMeanSEXP, SEXP survSdSEXP, SEXP fecundMeanSEXP, SEXP fecundSdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type start(startSEXP);
    Rcpp::traits::input_parameter< int >::type timesteps(timestepsSEXP);
    Rcpp::traits::input_parameter< double >::type survPhi(survPhiSEXP);
    Rcpp::traits::input_parameter< double >::type fecundPhi(fecundPhiSEXP);
    Rcpp::traits::input_parameter< double >::type survMean(survMeanSEXP);
    Rcpp::traits::input_parameter< double >::type survSd(survSdSEXP);
    Rcpp::traits::input_parameter< double >::type fecundMean(fecundMeanSEXP);
    Rcpp::traits::input_parameter< double >::type fecundSd(fecundSdSEXP);
    rcpp_result_gen = Rcpp::wrap(timeseries(start, timesteps, survPhi, fecundPhi, survMean, survSd, fecundMean, fecundSd));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_colorednoise_raw_noise", (DL_FUNC) &_colorednoise_raw_noise, 4},
    {"_colorednoise_timeseries", (DL_FUNC) &_colorednoise_timeseries, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_colorednoise(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
