# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate Autocorrelated Noise
#'
#' Generates temporally autocorrelated random numbers with a mean,
#' standard deviation, and autocorrelation you specify.
#' @param timesteps The number of temporally autocorrelated random numbers (one
#'   per timestep) you want.
#' @param mu The mean of the temporally autocorrelated random numbers.
#' @param sigma The standard deviation of the temporally autocorrelated random
#'   numbers.
#' @param phi The temporal autocorrelation. 0 is white noise (uncorrelated),
#'   positive values are red noise (directly correlated) and negative values are blue
#'   noise (inversely correlated).
#' @return A vector of temporally autocorrelated random numbers.
#' @examples
#' rednoise <- colored_noise(timesteps = 30, mu = 0.5, sigma = 0.2, phi = 0.3)
#' rednoise
#' @export
colored_noise <- function(timesteps, mu, sigma, phi) {
    .Call('_colorednoise_colored_noise', PACKAGE = 'colorednoise', timesteps, mu, sigma, phi)
}

#' Generate Correlated Normal Random Numbers
#'
#' Generate random numbers from a multivariate normal distribution.
#' It can be used to create correlated random numbers.
#' @param n The number of samples desired for each variable.
#' @param mu A vector giving the mean of each variable.
#' @param sigma A valid covariance matrix.
#' @return A matrix with n rows and as many columns as mu values.
#' @examples
#' mus <- c(0, 3, 5)
#' sigmas <- matrix(c(1, 0.265, 2.19, 0.265, 0.25, 0.66, 2.19, 0.66, 9), ncol = 3)
#' mat <- multi_rnorm(100, mus, sigmas)
#' var(mat)
#' @export
multi_rnorm <- function(n, mu, sigma) {
    .Call('_colorednoise_multi_rnorm', PACKAGE = 'colorednoise', n, mu, sigma)
}

#' Convert from Correlation Matrix to Covariance Matrix
#'
#' Convert a correlation matrix to a covariance matrix.
#' @param sigma A vector of standard deviations for the variables you're describing. Length must be the same as the number of rows/columns of CorrMatrix.
#' @param corrMatrix A valid correlation matrix.
#' @return A covariance matrix with the same dimensions as corrMatrix.
#' @examples
#' corr <- matrix(c(1, 0.53, 0.73, 0.53, 1, 0.44, 0.73, 0.44, 1), nrow = 3)
#' sigmas <- c(2, 0.3, 1.2)
#' covar <- cor2cov(sigmas, corr)
#' cov2cor(covar)
#' @export
cor2cov <- function(sigma, corrMatrix) {
    .Call('_colorednoise_cor2cov', PACKAGE = 'colorednoise', sigma, corrMatrix)
}

#' Generate Multiple Cross-Correlated & Autocorrelated Variables
#'
#' Generates random variables that are correlated to each other and temporally autocorrelated.
#' @param timesteps The number of temporally autocorrelated random numbers (one
#'   per timestep) you want.
#' @param mu A vector giving the mean of each variable.
#' @param sigma A vector giving the standard deviation of each variable.
#' @param phi A vector giving the temporal autocorrelation of each variable.
#' @param corrMatrix A valid correlation matrix. The number of rows/columns must match the length of the mu, sigma, and phi vectors.
#' @return A matrix with as many rows as timesteps and as many columns as mu/sigma/phi values.
#' @examples
#' corr <- matrix(c(1, 0.53, 0.73, 0.53, 1, 0.44, 0.73, 0.44, 1), nrow = 3)
#' test <- colored_multi_rnorm(100, c(0, 3, 5), c(1, 0.5, 1), corr, c(0.5, -0.3, 0))
#' var(test)
#' test %>% as.data.frame() %>% summarize_all(.funs = c("mean", "sd", "autocorrelation"))
#' @export
colored_multi_rnorm <- function(timesteps, mu, sigma, phi, corrMatrix) {
    .Call('_colorednoise_colored_multi_rnorm', PACKAGE = 'colorednoise', timesteps, mu, sigma, phi, corrMatrix)
}

variancefix <- function(mu, sigma, dist) {
    .Call('_colorednoise_variancefix', PACKAGE = 'colorednoise', mu, sigma, dist)
}

#' Simulated Time Series of an Unstructured Temporally Autocorrelated Population
#'
#' This function simulates an unstructured population with
#' temporally autocorrelated vital rates (survival and fertility). In other
#' words, this function will show you the dynamics over time of a population
#' whose survival and fertility is stochastic, but also correlated to the
#' survival and fertility in the previous year, respectively. The assumptions of the
#' simulation are that the population is asexually reproducing or female-only,
#' survival and fertility are the same at all ages / stages,
#' and that individuals continue to be reproductively capable until they die.
#'
#' Be advised that not all combinations of values will work. If you set survival and
#' fertility unrealistically high, the population size will tend toward infinity and
#' the simulation will fail because the numbers are too large to handle. Use your
#' common sense as a demographer / population biologist.
#' @import stats
#' @param start The starting population size.
#' @param timesteps The number of timesteps you want to simulate. Individuals
#'   are added and killed off every timestep according to the survival and
#'   fertility rates. In ecological applications, timesteps are usually years,
#'   but theoretically they can be any length of time.
#' @param survPhi The temporal autocorrelation of survival. 0 is white noise (uncorrelated),
#'   positive values are red noise (directly correlated) and negative values are
#'   blue noise (inversely correlated).
#' @param fecundPhi The temporal autocorrelation of fecundity. As above.
#' @param survMean The mean survival from timestep to timestep. Must be a value
#'   between 0 (all individuals die) and 1 (all individuals live).
#' @param survSd The standard deviation of the survival from timestep to
#'   timestep. Must be a value between 0 and 1.
#' @param fecundMean The mean fertility: mean offspring produced by each individual per timestep.
#' @param fecundSd The standard deviation of the fertility.
#' @return A data frame with four variables: timestep, population (total individuals
#'   alive at the start of the timestep), newborns (new individuals
#'   born this timestep), and survivors (individuals who survive this timestep).
#' @examples
#' series1 <- unstructured_pop(start = 20, timesteps = 10, survPhi = 0.7, fecundPhi = -0.1, survMean = 0.6,
#' survSd = 0.52, fecundMean = 1.2, fecundSd = 0.7)
#' head(series1)
#' @export
unstructured_pop <- function(start, timesteps, survPhi, fecundPhi, survMean, survSd, fecundMean, fecundSd) {
    .Call('_colorednoise_unstructured_pop', PACKAGE = 'colorednoise', start, timesteps, survPhi, fecundPhi, survMean, survSd, fecundMean, fecundSd)
}

projection <- function(initialPop, noise) {
    .Call('_colorednoise_projection', PACKAGE = 'colorednoise', initialPop, noise)
}

demo_stochasticity <- function(initialPop, rates) {
    .Call('_colorednoise_demo_stochasticity', PACKAGE = 'colorednoise', initialPop, rates)
}

